### ISSUE TITLE
Reproduce paper results

### ISSUE THREAD

**Issue by cdcseacave** [kysucix/gipuma#1]
First I want to say this is a valuable paper, and also thank you for sharing the code.

The code compiles fine (and seems to work fine also, though not very clear how to use it), but I have trouble reproducing the paper results. Could you please share with us an example script that reproduces one of the paper results?

For example, how to use the executable with the DTU object so that we get the result displayed in figure 1?

**Comment by kysucix** [comment]
Hi, thanks for your interest. I just commit the code yesterday and I did not have yet to document it. Now a basic description in online, I'll add a working example for DTU dataset and Middlebury the next week.

Silvano

**Comment by cdcseacave** [comment]
Thank you for the new scripts. However, trying to run dtu_accurate.sh results in multiple crashes, which seem to have to do with not enough video memory. I have an NVIDIA GTX970 with 3GB. What card is needed to run DTU scenes?

Also, I converted dtu_accurate.sh to a python script that processes PMVS projects. Please find it attached. On smaller scenes the depth-map computation works as expected, however the fusion step fails to produce any output (it produces only an empty ply file). Could you validate the script?

[pmvs_accurate.py.txt](https://github.com/kysucix/gipuma/files/57291/pmvs_accurate.py.txt)

**Comment by ORNis** [comment]
Hi Dan,
sorry for adding noise in this thread but if it could help I managed to run fusibile with PMVS dataset. if I remember well I hardcoded something in these lines  https://github.com/kysucix/fusibile/blob/master/main.cpp#L666-L671 (sorry for the lack of accuracy). Obviously I also added gencode for compute capabilities 3.0 (but you don't need that) and taking the missing file from gimpuma repo.

**Comment by kysucix** [comment]
Hi Dan, 
thanks for the new script. Right now I'm attending ICCV in Santiago so I do not have much time to validate the script, but I'll do it for sure, thanks. If I have your permission I will include as an alternative inside the repository.

For memory problem, 3GB should be more than enough. The thing is that fusibile is not that well optimized memory-wise. To obtain texture is loading every image into gpu memory in the same kernel that compute the resulting point cloud. I should probably split it in a separate kernel.

Again, we I'll be back I'll investigate and make sure the dtu results can be reproduced easily.
Ciao!
Silvano

**Comment by kysucix** [comment]
Hi dan,
you might test the whole pipeline with middlebury scripts. In this way we can really see if it's a memory problem

**Comment by kysucix** [comment]
and make sure that in the result folder for dtu there is just one folder per image. This might be the source of problems.

**Comment by kysucix** [comment]
feel free to copy and paste the output so that I can have an idea what is going on. please pull from fusibile before trying again. I checked and the memory needed for dtu is 2.3 GB Probably some memory can be saved without saving texture, I'll let you know when I'll work on it.

**Comment by cdcseacave** [comment]
The problem is not at the fusion step. I can not even estimate one single depth-map, all are crashing due to not enough video memory (looks like)

**Comment by kysucix** [comment]
Which command line you are using? Can you paste the output you get?

**Comment by cdcseacave** [comment]
I am using the script you provided: dtu_accurate. For ex:

Command line:
gipuma rect_001_3_r5000.png rect_002_3_r5000.png rect_003_3_r5000.png rect_004_3_r5000.png rect_005_3_r5000.png rect_006_3_r5000.png rect_007_3_r5000.png rect_008_3_r5000.png rect_009_3_r5000.png rect_010_3_r5000.png rect_011_3_r5000.png rect_012_3_r5000.png rect_013_3_r5000.png rect_014_3_r5000.png rect_015_3_r5000.png rect_016_3_r5000.png rect_017_3_r5000.png rect_018_3_r5000.png rect_019_3_r5000.png rect_020_3_r5000.png rect_021_3_r5000.png rect_022_3_r5000.png rect_023_3_r5000.png rect_024_3_r5000.png rect_025_3_r5000.png rect_026_3_r5000.png rect_027_3_r5000.png rect_028_3_r5000.png rect_029_3_r5000.png rect_030_3_r5000.png rect_031_3_r5000.png rect_032_3_r5000.png rect_033_3_r5000.png rect_034_3_r5000.png rect_035_3_r5000.png rect_036_3_r5000.png rect_037_3_r5000.png rect_038_3_r5000.png rect_039_3_r5000.png rect_040_3_r5000.png rect_041_3_r5000.png rect_042_3_r5000.png rect_043_3_r5000.png rect_044_3_r5000.png rect_045_3_r5000.png rect_046_3_r5000.png rect_047_3_r5000.png rect_048_3_r5000.png rect_049_3_r5000.png -images_folder "dtu/MVS Data/Rectified/scan6/" -p_folder "dtu/calib/" -output_folder "results/dtu_accurate_6" -no_display --algorithm=pm --ct_eps=2.5 --cam_scale=1 --iterations=8 --disp_tol=10 --norm_tol=0.2 --gtDepth_divisionFactor=1 --gtDepth_tolerance=0.1 --gtDepth_tolerance2=0.02 --blocksize=25 --cost_gamma=10 --cost_comb=best_n --n_best=3 --depth_max=800 --depth_min=300 -view_selection --min_angle=10 --max_angle=30


Result:
Command-line parameter warning: unknown option -no_display
Pmvs path is 
Input files are rect_002_3_r5000.png
Input files are rect_001_3_r5000.png
Input files are rect_003_3_r5000.png
Input files are rect_004_3_r5000.png
Input files are rect_005_3_r5000.png
Input files are rect_006_3_r5000.png
Input files are rect_007_3_r5000.png
Input files are rect_008_3_r5000.png
Input files are rect_009_3_r5000.png
Input files are rect_010_3_r5000.png
Input files are rect_011_3_r5000.png
Input files are rect_012_3_r5000.png
Input files are rect_013_3_r5000.png
Input files are rect_014_3_r5000.png
Input files are rect_015_3_r5000.png
Input files are rect_016_3_r5000.png
Input files are rect_017_3_r5000.png
Input files are rect_018_3_r5000.png
Input files are rect_019_3_r5000.png
Input files are rect_020_3_r5000.png
Input files are rect_021_3_r5000.png
Input files are rect_022_3_r5000.png
Input files are rect_023_3_r5000.png
Input files are rect_024_3_r5000.png
Input files are rect_025_3_r5000.png
Input files are rect_026_3_r5000.png
Input files are rect_027_3_r5000.png
Input files are rect_028_3_r5000.png
Input files are rect_029_3_r5000.png
Input files are rect_030_3_r5000.png
Input files are rect_031_3_r5000.png
Input files are rect_032_3_r5000.png
Input files are rect_033_3_r5000.png
Input files are rect_034_3_r5000.png
Input files are rect_035_3_r5000.png
Input files are rect_036_3_r5000.png
Input files are rect_037_3_r5000.png
Input files are rect_038_3_r5000.png
Input files are rect_039_3_r5000.png
Input files are rect_040_3_r5000.png
Input files are rect_041_3_r5000.png
Input files are rect_042_3_r5000.png
Input files are rect_043_3_r5000.png
Input files are rect_044_3_r5000.png
Input files are rect_045_3_r5000.png
Input files are rect_046_3_r5000.png
Input files are rect_047_3_r5000.png
Input files are rect_048_3_r5000.png
Input files are rect_049_3_r5000.png
GlobalState constructor
Accepted intersection angle of central rays is 10.000000 to 30.000000 degrees
Accepting camera 1 with angle	 12.471171 degree (0.217663 radians) and baseline 128.911514
Accepting camera 2 with angle	 12.559912 degree (0.219212 radians) and baseline 130.205551
Accepting camera 3 with angle	 24.499512 degree (0.427597 radians) and baseline 252.761429
Accepting camera 7 with angle	 24.961674 degree (0.435663 radians) and baseline 259.991150
Accepting camera 8 with angle	 16.576647 degree (0.289317 radians) and baseline 174.470367
Accepting camera 9 with angle	 11.163996 degree (0.194848 radians) and baseline 119.263733
Accepting camera 10 with angle	 13.535170 degree (0.236233 radians) and baseline 143.112427
Accepting camera 12 with angle	 25.134163 degree (0.438674 radians) and baseline 264.231567
Accepting camera 13 with angle	 22.287561 degree (0.388991 radians) and baseline 236.055771
Accepting camera 14 with angle	 22.986954 degree (0.401198 radians) and baseline 243.496429
Accepting camera 15 with angle	 26.888401 degree (0.469291 radians) and baseline 283.301544
Range of Minimum/Maximum depth is: 300 800
Selected views: 9
3, 8, 2, 10, 14, 15, 1, 13, 9, 
Range of Minimum/Maximum depth is: 1.95232 5.2062

**Comment by kysucix** [comment]
Hi Dan, I checked and computing the depthmap on dtu uses less than 1G of memory. It should not be that the problem. Which kind of crash do you get? Segfault? Are you sure you download correctly the data? Are you running it on windows?

The fusion for smaller dataset should be fixed now

**Comment by kysucix** [comment]
Hi Dan, can you reproduce dtu results with latest git commits? Silvano

**Comment by cdcseacave** [comment]
Hi Silvano!

Yes, now it works, but only on Linux, not on Windows.

Thank you!

**Comment by kysucix** [comment]
Great! Please open a new issue in case you would like to debug the windows version. Silvano
