### ISSUE TITLE
Documentation for how to specify camera parameters?

### ISSUE THREAD

**Issue by drewm1980** [kysucix/gipuma#11]
I have parameters, including intrinsics, extrinsics, and a radial distortion model, for my camera array.  The camera calibration was done in HALCON, so I'm expecting to have to write a config file of some sort for gipuma.

How do you specify camera parameters for your camera array to gipuma?  

I don't see any radial distortion related stuff in CameraGeometryUtils.h. Does this mean gipuma only takes pre-warped images? 

Thanks!

**Comment by kysucix** [comment]
Hi,

yes you are right, the input images have to be corrected for radial distortions, gipuma does not do it on its own. You can obtain radially corrected images easily with [vsfm](http://ccwu.me/vsfm/index.html)

**Comment by drewm1980** [comment]
Hi! Thanks for the response and for sharing your code!

Do the images need to be in rectified pairs, or just radially un-distorted?

**Comment by kysucix** [comment]
Just radially undistorted.
