### ISSUE TITLE
Segmentation fault (core dump)

### ISSUE THREAD

**Issue by chuong** [kysucix/gipuma#12]
First thank you for sharing the state of the art code. 

I got segmentation fault errors when running on my Ubuntu 14.04-64bit with 8GB RAM, GeForce 840M with 2GB memory and Cuda 7.5. 
`./scripts/dino.sh: line 28:  3970 Segmentation fault      (core dumped) $cmd
10
...`
I ran some other Cuda test and it worked. So not sure what is the source of error when running GIPUMA.

Many thanks.

**Comment by chuong** [comment]
Using ``printf`` statements, I found that the segmentation happens to ``gipuma(GlobalState &gs)`` function, inside pragma condition:
``#ifndef SHARED_HARDCODED
..
#else``
This is very confusing.

**Comment by drewm1980** [comment]
An 840M is compute capability 5.0 according to wikipedia, so that's high enough. 

It could be you're just running out of gpu ram. I'd try on a workstation if you have one handy, or with fewer images. gipuma reports the amount of video ram it will use; you could compare that number to your laptop laptop's spec sheet.

You can also try PMVS2 if you haven't already; gipuma claims to accept the same input, though I haven't gotten it to work yet.

**Comment by drewm1980** [comment]
Update: I am also getting a segfault when trying to run with a krt file:

For some reason the program just freezes in gdb, but in valgrind I can get a clue:
```
==5655==    at 0x61D9500: std::string::length() const (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19)
==5655==    by 0x4223F6: runGipuma(InputFiles&, OutputFiles&, AlgorithmParameters&, GTcheckParameters&, Results&) (in /home/awagner/src/gipuma/gipuma)
==5655==    by 0x426ED1: main (in /home/awagner/src/gipuma/gipuma)
==5655==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
```

Here are the contents of my krt file:
```
$ cat data/name_par.txt 
image00.png 3619.60112093 0.0 698.920776775 0.0 3616.54856121 571.744949338 0.0 0.0 1.0 0.747173 -0.001568 -0.664628 -0.019976 0.999492 -0.024815 0.66433 0.031818 0.746762 -0.00017375603 -0.012240670282 0.181571526334
image01.png 3617.7777623 0.0 654.580368306 0.0 3620.2313158 555.039153087 0.0 0.0 1.0 0.984257 0.000837 -0.176738 -0.00776 0.999229 -0.038481 0.17657 0.039247 0.983505 -0.000960979996 -0.014127722115 0.176464156951
image02.png 3591.68232655 0.0 657.399107653 0.0 3596.60255777 586.290981129 0.0 0.0 1.0 0.928202 0.007891 0.371993 0.009051 0.999 -0.043778 -0.371967 0.044001 0.927203 -0.006531243666 -0.016119434395 0.198261952369
image03.png 3605.75829014 0.0 618.801518466 0.0 3609.72340591 592.166414846 0.0 0.0 1.0 0.644227 0.004864 0.764819 0.003555 0.99995 -0.009353 -0.764826 0.008744 0.644177 -0.013492080642 -0.007860512994 0.207417134516
```

**Comment by drewm1980** [comment]
My tools are failing me... gdb still crashes when I put the breakpoint on the line valgrind says is in the backtrace of the crash.

```
Reading symbols from /home/awagner/src/gipuma/gipuma...done.
(gdb) b runGipuma(InputFiles&, OutputFiles&, AlgorithmParameters&, GTcheckParameters&, Results&) 
Breakpoint 1 at 0x42235f
(gdb) run -krt_file data/name_par.txt
Starting program: /home/awagner/src/gipuma/gipuma -krt_file data/name_par.txt
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
```

**Comment by drewm1980** [comment]
@chuong I found at least one codepath that segfaults instead of throwing a meaningful error and fixed it up. If you want you can try my fork (or this one if my pull request is accepted), and you may at least get a meaningful error.
