### ISSUE TITLE
fix for windows

### ISSUE THREAD

**Issue by cdcseacave** [kysucix/gipuma#2]
small fix for windows

[gipuma.diff.txt](https://github.com/kysucix/gipuma/files/46281/gipuma.diff.txt)

**Comment by Just5D** [comment]
cudaArray *cuArray[i]; //vs2013 err

**Comment by kysucix** [comment]
Thanks guys I fixed it. Did you use cmake to compile it for windows or you had to configure it manually? Could you provide your Visual Studio project so that I can include it in the project?

**Comment by cdcseacave** [comment]
no need for the VS project, the cmake script you made works just fine

**Comment by kysucix** [comment]
even better, thanks. Silvano
