### ISSUE TITLE
reduce the image loaded for computing to max_views

### ISSUE THREAD

**Issue by saedrna** [kysucix/gipuma#23]
Is it for a historical reason that gipuma will load all the images for computing? Even if views are selected?

Because in computing the depth for a reference image, only the selected views are used, e.g.  gipuma.cu, line 742 in the master version.

```
for ( int i = 0; i < camParams.viewSelectionSubsetNumber; i++ )
    int idxCurr = camParams.viewSelectionSubset[i];
```

`

However, even if only the selected views are processed, all the images are loaded into CPU and uploaded to GPU, as

```
 for ( size_t i = 0; i < numImages; i++ ) {
        img_grayscale[i] = imread ( ( inputFiles.images_folder + inputFiles.img_filenames[i] ), IMREAD_GRAYSCALE );
        if ( algParams.color_processing ) {
            img_color[i] = imread ( ( inputFiles.images_folder + inputFiles.img_filenames[i] ), IMREAD_COLOR );
        }

        if ( img_grayscale[i].rows == 0 ) {
            printf ( "Image seems to be invalid\n" );
            return -1;
        }
    }
```

and

```
    if (algParams.color_processing)
        addImageToTextureFloatColor (img_color_float_alpha, gs->imgs, gs->cuArray);
    else
        addImageToTextureFloatGray (img_grayscale_float, gs->imgs, gs->cuArray);
```

Is this problem able to be handled in gipuma and fusibile? Because in real datasets with off-the-shelf camera, e.g. cell phones with 12MP and mirrorless camera with 24MP, the memory will easily explode for a small datasets.

Thanks, 

Han

**Comment by drewm1980** [comment]
@saedrna reconstruction takes a couple seconds per depth map few 2MP images on my Titan X.  Extrapolate that to a cell phone on larger images, and you're probably looking at minutes per frame.
