### ISSUE TITLE
Undocumented parameters

### ISSUE THREAD

**Issue by drewm1980** [kysucix/gipuma#25]
I am looking in gipuma/scripts/dinoSpareRing.sh.

It looks like you had to manually tune a bunch of undocumented parameters to make the reconstruction work.  Is that true? Or is there just a bunch of DRY violation in the shell scripts you used to glue gipuma/fusibile together? I am worried about whether gipuma is capable at all of running on generic data.

**Comment by kysucix** [comment]
hi Andrew, I understand you concert.
You can safely remove the parameters the following parameters as they do not contribute at all at the reconstruction, they are "leftover" from previous code:
-no_display --algorithm=pm --ct_eps=2.5 --disp_tol=10 --norm_tol=0.2 --gtDepth_divisionFactor=1 --gtDepth_tolerance=0.1 --gtDepth_tolerance2=0.02

**Comment by drewm1980** [comment]
OK, I noticed you are doing some work cleaning up the shell scripts. Thanks!
