### ISSUE TITLE
Incorrect results for DTU on Tesla K80 

### ISSUE THREAD

**Issue by hollownike** [kysucix/gipuma#26]
Hi!

First I would like to thank you for making your code publicly accessible.

I could compile and run your code with the DTU dataset on my local machine that has a single GTX 960 with 1995MB memory and everything seemed fine. Then I tried the same on our server with multiple Tesla K80 with each 11519MB memory. There the results for the individual keyviews appear incomplete and incorrect. The depth map as well as the dist.png seem to include only the first 50 image columns and they appear to be incorrect or at least include additional noise.

Results on server with Tesla K80:
![dist.png](https://cloud.githubusercontent.com/assets/457081/20302275/e46a8ae4-ab26-11e6-85d6-171dde5545e8.png)
![3d_model0.ply-0](https://cloud.githubusercontent.com/assets/457081/20302369/42deabe6-ab27-11e6-95df-c19c93076c11.png)
![3d_model0.ply-1](https://cloud.githubusercontent.com/assets/457081/20304172/2f4947a0-ab2f-11e6-8279-4a8e50725af8.png)
![3d_model0.ply-2](https://cloud.githubusercontent.com/assets/457081/20304176/30fe83f8-ab2f-11e6-9a34-beb9daf32cb3.png)

The final model that was produced on the server looks as if it is acceptable though.
![final-server](https://cloud.githubusercontent.com/assets/457081/20304239/8038ffca-ab2f-11e6-95d9-c8594c9db90b.png)

I always restricted the code to run on one card only (although not always the same) and called

\> CUDA_VISIBLE_DEVICES=0 ./gipuma/scripts/dtu_fast.sh 1

The Cuda compilation tools are at release 7.5, V7.5.17 on both systems. The relative paths to the data are equal as well. In both cases I used the checked in calibration files in gipuma/data/dtu/calib/.

I am currently working on my masters thesis and would like to include and build on your work. Sadly my local GPU (GTX 960) lacks the memory necessary for the fuse step so I cannot reproduce the published results.

  

Sincerely,
Nikolaus Heran

**Comment by Li-Shang** [comment]
I got similar problem problem. did you resolve this? Thanks.

**Comment by kysucix** [comment]
The current cmake it's enable all recent cuda architecture, you should be able to run it successfully on recent video card now.
