### ISSUE TITLE
Debug mode in Visual studio 2015

### ISSUE THREAD

**Issue by kemyoung** [kysucix/gipuma#29]
If I create a visual studio 2015 solution using CMake and compile it, it will run in release mode well. However, the following error occurs in debug mode.
Error Code D8016	'/RTC1' and '/O2' command-line options are incompatible.

**Comment by sanghunpark** [comment]
I had exactly the same problem in VS2015 and I have found the solution

You have to only use one of two command-line options as indicated by the error message but could not change these options in the Project Property page of Visual Studio.

It can be resolved by changing values in the CMake entries ('CAMKE_CXX_FLAGS_DEBUG' and 'CMAKE_C_FLAGS_DEBUG').
I set them to '/MDd /Zi /Ob0 /Od'.
