### ISSUE TITLE
segmentation fault (core dumped), run on Ubuntu 16.04

### ISSUE THREAD

**Issue by HKUSTmji** [kysucix/gipuma#31]
Thank you a lot to release this code. I successfully run this code on a Ubuntu 14.04 machine. However got the following segmentation fault, and I'm not sure the 16.04 version matters or not? Any suggestions please?

command: `./scripts/dtu_accurate.sh 11`

printouts: 
0
/home/mengqi/fileserver/datasets/DTU_MVS/Rectified/scan11/./gipuma rect_001_3_r5000.png rect_002_3_r5000.png rect_003_3_r5000.png rect_004_3_r5000.png rect_005_3_r5000.png rect_006_3_r5000.png rect_007_3_r5000.png rect_008_3_r5000.png rect_009_3_r5000.png rect_010_3_r5000.png rect_011_3_r5000.png rect_012_3_r5000.png rect_013_3_r5000.png rect_014_3_r5000.png rect_015_3_r5000.png rect_016_3_r5000.png rect_017_3_r5000.png rect_018_3_r5000.png rect_019_3_r5000.png rect_020_3_r5000.png rect_021_3_r5000.png rect_022_3_r5000.png rect_023_3_r5000.png rect_024_3_r5000.png rect_025_3_r5000.png rect_026_3_r5000.png rect_027_3_r5000.png rect_028_3_r5000.png rect_029_3_r5000.png rect_030_3_r5000.png rect_031_3_r5000.png rect_032_3_r5000.png rect_033_3_r5000.png rect_034_3_r5000.png rect_035_3_r5000.png rect_036_3_r5000.png rect_037_3_r5000.png rect_038_3_r5000.png rect_039_3_r5000.png rect_040_3_r5000.png rect_041_3_r5000.png rect_042_3_r5000.png rect_043_3_r5000.png rect_044_3_r5000.png rect_045_3_r5000.png rect_046_3_r5000.png rect_047_3_r5000.png rect_048_3_r5000.png rect_049_3_r5000.png -images_folder /home/mengqi/fileserver/datasets/DTU_MVS/Rectified/scan11/ -p_folder data/dtu/calib/ -output_folder // -no_display --algorithm=pm --ct_eps=2.5 --cam_scale=1 --iterations=8 --disp_tol=10 --norm_tol=0.2 --gtDepth_divisionFactor=1 -ng rect_049_3_r5000.png -images_folder /home/mengqi/fileserver/datasets/DTU_MVS/Rectified/scan11/ -p_folder data/dtu/calib/ -output_folder // -no_display --algorithm=pm --ct_eps=2.5 --cam_scale=1 --iterations=8 --disp_tol=10 --norm_tol=0.2 --gtDepth_divisionFactor=1 --gtDepth_tolerance=0.1 --gtDepth_tolerance2=0.02 --blocksize=25 --cost_gamma=10 --cost_comb=best_n --n_best=3 --depth_max=800 --depth_min=300 -view_selection --min_angle=10 --max_angle=30
Command-line parameter warning: unknown option -no_display
Input files are: rect_001_3_r5000.png rect_002_3_r5000.png rect_003_3_r5000.png rect_004_3_r5000.png rect_005_3_r5000.png rect_006_3_r5000.png rect_007_3_r5000.png rect_008_3_r5000.png rect_009_3_r5000.png rect_010_3_r5000.png rect_011_3_r5000.png rect_012_3_r5000.png
 rect_013_3_r5000.png rect_014_3_r5000.png rect_015_3_r5000.png rect_016_3_r5000.png rect_017_3_r5000.png rect_018_3_r5000.png rect_019_3_r5000.png rect_020_3_r5000.png rect_021_3_r5000.png rect_022_3_r5000.png rect_023_3_r5000.png rect_024_3_r5000.png rect_025_3_r5000.png rect_026_3_r5000.png rect_027_3_r5000.png rect_028_3_r5000.png rect_029_3_r5000.png rect_030_3_r5000.png rect_031_3_r5000.png rect_032_3_r5000.png rect_033_3_r5000.png rect_034_3_r5000.png rect_035_3_r5000.png rect_036_3_r5000.png rect_037_3_r5000.png rect_038_3_r5000.png rect_039_3_r5000.png rect_040_3_r5000.png rect_041_3_r5000.png rect_042_3_r5000.png rect_043_3_r5000.png rect_044_3_r5000.png rect_045_3_r5000.png rect_046_3_r5000.png rect_047_3_r5000.png rect_048_3_r5000.png rect_049_3_r5000.png
Detected 4 devices!
Detected gipuma compatible device: Graphics Device
Accepting intersection angle of central rays from 10.000000 to 30.000000 degrees, use --min_angle=<angle> and --max_angle=<angle> to m
odify them
Total number of images used: 8
Selected views: 1, 2, 8, 9, 10, 11, 12, 13,
Range of Minimum/Maximum depth is: 1.95232 5.20619, change it with --depth_min=<value> and  --depth_max=<value>
Device memory used: 795.017212MB
Blocksize is 25x25
Number of iterations is 8
Iteration 1 2 3 4 5 6 7 8
                Total time needed for computation: 6.766714 seconds
./scripts/dtu_accurate.sh: line 29:  **_`2333 Segmentation fault      (core dumped)`_** $prog ${image_list[@]} -images_folder "$inputdir" -p_folder $p_folder -output_folder $output_dir -no_display --algorithm=pm --ct_eps=2.5 --cam_scale=$scale --iterations=$iter --disp_tol=10 --norm_tol=0.2 --gtDepth_divisionFactor=1 --gtDepth_tolerance=0.1 --gtDepth_tolerance2=0.02 --blocksize=$blocksize --cost_gamma=$cost_gamma --cost_comb=best_n --n_best=$n_best --depth_max=$depth_max --depth_min=$depth_min -view_selection --min_angle=$min_angle --max_angle=$max_angle
1
/home/mengqi/fileserver/datasets/DTU_MVS/Rectified/scan11/./gipuma rect_002_3_r5000.png rect_001_3_r5000.png rect_003_3_r5000.png rect_004_3_r5000.png rect_005_3_r5000.png rect_006_3_r5000.png rect_007_3_r5000.png rect_008_3_r5000.png rect_009_3_r5000.png rect_010_3_r
5000.png rect_011_3_r5000.png rect_012_3_r5000.png rect_013_3_r5000.png rect_014_3_r5000.png rect_015_3_r5000.png rect_016_3_r5000.png rect_017_3_r5000.png rect_018_3_r5000.png rect_019_3_r5000.png rect_020_3_r5000.png rect_021_3_r5000.png rect_022_3_r5000.png rect_02
...

**Comment by shubhamag** [comment]
Facing the same issue,  Ubuntu 16.04 and Cuda 8
