### ISSUE TITLE
no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by shenqiguanghuan** [kysucix/gipuma#35]
OS: win10
Platform: VS2015
CUDA: 9.0
GPU: GTX 950M(compute capacity 5.0)
Driver version: 388.73
I compiled and generated this code well with CMake. However, when running this on templeSparseRing data or other test data, I had the "no kernel image is available for execution on the device" error, then I repalced the string "-gencode arch=compute_30,code=sm_30 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_61,code=sm_61" with "-gencode arch=compute_50,code=sm_50" in CMakeLists.txt, I also change the code generation value to compute_50, sm_50 on the project property page in VS, but neither seems to work. 
Any advices are welcome:)
Output:
./gipuma templeSR0001.png templeSR0002.png templeSR0003.png templeSR0004.png templeSR0005.png -images_folder data/templeSparseRing/ -krt_file data/templeSparseRing/templeSR_par.txt -output_folder results/templeSparseRing/ -no_display --cam_scale=1 --iterations=8 --blocksize=11 --cost_gamma=10 --cost_comb=best_n --n_best=2 --depth_max=0.8 --depth_min=0.3 --min_angle=5 --max_angle=70
Command-line parameter warning: unknown option -no_display
Input files are: templeSR0001.png templeSR0002.png templeSR0003.png templeSR0004.png templeSR0005.png
Detected 1 devices!
Detected gipuma compatible device: GeForce GTX 950M
Accepting intersection angle of central rays from 5.000000 to 70.000000 degrees, use --min_angle=<angle> and --max_angle=<angle> to modify them
Total number of images used: 1
Selected views: 1,
Range of Minimum/Maximum depth is: 1026.27 2736.72, change it with --depth_min=<value> and  --depth_max=<value>
Device memory used: 642.822998MB
Blocksize is 11x11
Number of iterations is 8
Iteration 1 2 3 4 5 6 7 8
                Total time needed for computation: 0.002229 seconds
Error: no kernel image is available for execution on the device
Saving output depthmap in results/templeSparseRing//20190305_092740_templeSR0001/3d_model0.ply
Total runtime including disk i/o: 0.479357sec

**Comment by iabaldwin** [comment]
Hey @shenqiguanghuan, and whoever else comes to this - just had the same issue, CUDA 10.0 with Titan X. I had to change `find_package` to CUDA 10.0, and then substituted the arch compilation compatibility flags for my CUDA version from this page:
https://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/
This worked as expected. Hopefully that helps!
