### ISSUE TITLE
results on TUM dataset are really bad

### ISSUE THREAD

**Issue by Li-Shang** [kysucix/gipuma#37]
I'd like to use gipuma on TUM or some other SLAM dataset to get depthmap. But it got really bad results.
![c1](https://user-images.githubusercontent.com/18007584/60750009-f4c5d600-9fd4-11e9-912b-45fecf19cf8d.PNG)
the normal image is :
![normals](https://user-images.githubusercontent.com/18007584/60750039-66058900-9fd5-11e9-9f98-72623021a190.png)

I used these parameters:

> Cost function: PatchMatch Cost
  Kernel size: 19 x 19
  Number of iterations: 8
  Max. disparity: 256
  Depth min: 0.4
  Depth max: 3
  gamma: 10
  alpha: 0.9
  tauCol: 10
  tauGrad: 2
  border value: -1
  disparity tolerance (occ check): 1
  normal tolerance (occ check): 0.1
  census epsilon: 2.5
  self-similarity n: 50
  cost good truncation factor: 1.5
  cost combination: BEST_N (n=3)
  color processing: yes
  view selection: yes
  GT disparity tolerance: 0.5

**Comment by Li-Shang** [comment]
it has incorrect results on DTU dataset, too.
![disp](https://user-images.githubusercontent.com/18007584/61613629-d7794480-ac2f-11e9-936a-d5e1d7fee0da.png)
![Screenshot from 2019-07-22 03-22-37](https://user-images.githubusercontent.com/18007584/61613693-02fc2f00-ac30-11e9-9eda-01e0c92bf22a.png)

**Comment by kysucix** [comment]
Hi, you should fuse all the depthmap with fusibile, the single depthmap are noisy by construction.

**Comment by da-carte** [comment]
Li-Shang were you editing an existing bash file to get some results. I have tried but getting zero output.
