### ISSUE TITLE
Undefined symbol lookup

### ISSUE THREAD

**Issue by ben-parfitt** [kysucix/gipuma#39]
`./gipuma: symbol lookup error: ./gipuma: undefined symbol: _ZN2cv6imreadERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEi`
For all images when running the dinoSparse.
I compiled openCV on my own machine, where I am now running gipuma. Any advice would be appreciated.

**Comment by kysucix** [comment]
Hi ben, please double check your installation. I suggest to use the precompiled version of your operating system.

**Comment by ben-parfitt** [comment]
Yeah I just needed to restart my computer to resolve the issue
