### ISSUE TITLE
Binary Masks/Silhouette management

### ISSUE THREAD

**Issue by vLerent** [kysucix/gipuma#7]
Hello,
First of all, congrats for this valuable paper and also for making the source code available.

Everything compiled fine and I am able to reproduce paper's results. I am now trying to run it on a 68 cameras dataset with a green background, (background segmentation is available). This uniform background is causing me troubles as it creates a lot of unwanted noise, did you implement / is there a simple way I could use silhouette information as input to prevent wrong reconstructions?

Also, if I replaced background with random noise, it wouldn't be coherent between cameras, and points would not be reconstructed... could this work? 

Thanks for your help,

Vincent

**Comment by kysucix** [comment]
hi Vincent,

I still did not implement any silhouette removal tool, there is an hardcoded and simple background trick in fusibile (fusibile.cu line 254) to remove background on middlebury images, maybe you can adapt that to remove the background.

Maybe the trick to add background noise might solve your issue, just try! :)

Ciao,
Silvano
