### ISSUE TITLE
project generate failed

### ISSUE THREAD

**Issue by riyueshi** [kysucix/gipuma#8]
hi,
  while I compile the project using cmake, I got a error message as following:
  "Building NVCC (Device) object CMakeFiles/gipuma.dir/Release/gipuma_generated_gipuma.cu.obj
  nvcc fatal   : Unsupported gpu architecture 'compute_52' 
  CMake Error at gipuma_generated_gipuma.cu.obj.cmake:207 (message):
    Error generating
    F:/GitHub/gipuma/build/CMakeFiles/gipuma.dir//Release/gipuma_generated_gipuma.cu.obj
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(170,5): error MSB6006: “cmd.exe” "

   It seems something wrong with my graphics card, but I don't know how to fix it.
   the cmake configured fine and can generate successfully, but the VS2013 just can not generated the project, did I missed any thing? the following is the environment I used to configure the project: GPU: GTX 650 (seems meet the requirements of compute capability 3.0)  OS: Windows 7, IDE: VS2013, CUDA Toolkit 6.5, opencv 3.0 , cmake 3.4.
   And thanks for sharing your code :)

**Comment by kysucix** [comment]
Hi riyueshi,

inside CMakeLists.txt I tell the cuda compiler to compile both for "old" and new architectures (compute capabilities 3.0 and 5.2) and at runtime the program should know which one to run. Probably this does not work inside VS2013.
I suggest to remove the string " -gencode arch=compute_52,code=sm_52" in line 10 of CMakeLists.txt and try to compile it again.
Let me know.

Ciao,
Silvano

**Comment by riyueshi** [comment]
Hi Silvano,
It is great that your tip works to fix the last problem :). however I got the following problem: 
1, the file "dirent.h" required in the main.cpp does not exit in Windows platform, and i find an version of "dirent.h" under Windows platform to fix the problem. 
2, there is an Compiler Error C2491 located at "mathUtils.h" line 14,and i commented the function "roundf" fixed the problem (I don't know whether this would result in an mistake to the project ).
3, the release mode can generate the executable file but crashed while runing after step 1 and 2, but the debug mode got a error "Command line error work016 : '/O1' and '/RTC1' command-line options are incompatible"(I googled it the solution i find seems doesn't work) ,since I can not debug the code I don't know how to handle it.
is there any advice to fix those problem. (I am not familiar with Linux, perhaps I should try run the project on Linux OS T_T  )
Thanks,
Miller Zhang

**Comment by parapapa1** [comment]
Maybe I could help, I try to run the program from windows visual studio 2015, but after loading the entire folder, this error appears

** Program 'c:\Users\10\Downloads\gipuma-master/app.js' does not exist.

I appreciate if you can tell me where you can be the error. thank you very much for your attention

**Comment by riyueshi** [comment]
@parapapa1, the problem you meet doesn't occurred in my case. Sorry for that I don't have any idea that may help.
